"use client";

import {Pencil, Plus, Trash2, X} from "lucide-react";
import {useTranslations} from "next-intl";
import {useState, type FormEvent} from "react";

import {Button} from "@/components/ui/button";
import {Card, CardContent, CardHeader, CardTitle} from "@/components/ui/card";
import {ErrorMessage} from "@/components/ui/error-message";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select} from "@/components/ui/select";
import {Textarea} from "@/components/ui/textarea";
import type {Brand, CategoryTree} from "@/lib/api/types";

import {useBrands, useCategories} from "@/features/catalog/queries";
import {useCreateAdminBrand, useCreateAdminCategory, useCreateAdminProduct, useDeleteAdminBrand, useDeleteAdminCategory, useUpdateAdminBrand, useUpdateAdminCategory} from "./queries";

export function CategoryManagement() {
  const t = useTranslations("admin");
  const categories = useCategories();
  const create = useCreateAdminCategory();
  const remove = useDeleteAdminCategory();
  const update = useUpdateAdminCategory();
  const [form, setForm] = useState({name: "", seoName: "", parentId: ""});
  const [editing, setEditing] = useState<CategoryTree | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); await create.mutateAsync({name: form.name.trim(), seoName: form.seoName.trim(), parentId: form.parentId || undefined}); setForm({name: "", seoName: "", parentId: ""}); }
  const flat = flatten(categories.data ?? []);
  return <section className="space-y-6"><Card><CardHeader><CardTitle>{t("createCategory")}</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-3" onSubmit={(event) => void submit(event)}><Field id="category-name" label={t("name")} value={form.name} onChange={(value) => setForm((current) => ({...current, name: value}))} required /><Field id="category-seo" label={t("seoName")} value={form.seoName} onChange={(value) => setForm((current) => ({...current, seoName: value}))} required /><div className="space-y-2"><Label htmlFor="category-parent">{t("parentCategory")}</Label><Select id="category-parent" value={form.parentId} onChange={(event) => setForm((current) => ({...current, parentId: event.target.value}))}><option value="">{t("rootCategory")}</option>{flat.map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</Select></div><Button type="submit" className="md:col-span-3" disabled={create.isPending}><Plus className="size-4" />{t("create")}</Button>{create.isError ? <div className="md:col-span-3"><ErrorMessage error={create.error} /></div> : null}</form></CardContent></Card>{editing ? <CategoryEditForm category={editing} categories={flat} onClose={() => setEditing(null)} onSave={(request) => update.mutateAsync({id: editing.id!, request})} loading={update.isPending} error={update.error} /> : null}<Card><CardHeader><CardTitle>{t("categoryTree")}</CardTitle></CardHeader><CardContent>{categories.isPending ? <div className="h-24 animate-pulse rounded-xl bg-muted" /> : categories.isError ? <ErrorMessage error={categories.error} /> : <div className="space-y-2">{flat.map((category) => <div key={category.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span>{category.label}</span><div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => setEditing((categories.data ?? []).flatMap((item) => findCategory(item, category.id) ? [findCategory(item, category.id)!] : [])[0] ?? {id: category.id, name: category.label.replace(/^—+\s*/, ""), seoName: "", parentId: undefined})} aria-label={t("editCategory")}><Pencil className="size-4" /></Button><Button size="icon-sm" variant="ghost" className="text-destructive hover:text-destructive" onClick={() => {if (window.confirm(t("confirmDelete"))) void remove.mutateAsync(category.id);}} disabled={remove.isPending} aria-label={t("delete")}><Trash2 className="size-4" /></Button></div></div>)}</div>}{remove.isError ? <div className="mt-4"><ErrorMessage error={remove.error} /></div> : null}</CardContent></Card></section>;
}

function findCategory(category: CategoryTree, id?: string): CategoryTree | null { if (category.id === id) return category; for (const child of category.children ?? []) { const found = findCategory(child, id); if (found) return found; } return null; }
function CategoryEditForm({category, categories, onClose, onSave, loading, error}: {category: CategoryTree; categories: {id: string; label: string}[]; onClose: () => void; onSave: (request: {name: string; seoName: string; parentId?: string; status?: string}) => Promise<unknown>; loading: boolean; error: unknown}) {
  const t = useTranslations("admin");
  const [form, setForm] = useState({name: category.name ?? "", seoName: category.seoName ?? "", parentId: category.parentId ?? "", status: category.status ?? "ACTIVE"});
  async function submit(event: FormEvent) { event.preventDefault(); await onSave({name: form.name.trim(), seoName: form.seoName.trim(), parentId: form.parentId || undefined, status: form.status}); onClose(); }
  return <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>{t("editCategory")}</CardTitle><Button size="icon-sm" variant="ghost" onClick={onClose} aria-label={t("close")}><X className="size-4" /></Button></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-4" onSubmit={(event) => void submit(event)}><Field id="edit-category-name" label={t("name")} value={form.name} onChange={(value) => setForm((current) => ({...current, name: value}))} required /><Field id="edit-category-seo" label={t("seoName")} value={form.seoName} onChange={(value) => setForm((current) => ({...current, seoName: value}))} required /><Select value={form.parentId} onChange={(event) => setForm((current) => ({...current, parentId: event.target.value}))}><option value="">{t("rootCategory")}</option>{categories.filter((item) => item.id !== category.id).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</Select><Select value={form.status} onChange={(event) => setForm((current) => ({...current, status: event.target.value}))}><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></Select><div className="flex gap-2 md:col-span-4"><Button type="submit" disabled={loading}>{t("save")}</Button><Button type="button" variant="outline" onClick={onClose}>{t("cancel")}</Button></div>{error ? <div className="md:col-span-4"><ErrorMessage error={error} /></div> : null}</form></CardContent></Card>;
}

export function BrandManagement() {
  const t = useTranslations("admin");
  const brands = useBrands();
  const create = useCreateAdminBrand();
  const remove = useDeleteAdminBrand();
  const update = useUpdateAdminBrand();
  const [form, setForm] = useState({name: "", description: ""});
  const [editing, setEditing] = useState<Brand | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); await create.mutateAsync({name: form.name.trim(), description: form.description.trim() || undefined}); setForm({name: "", description: ""}); }
  return <section className="space-y-6"><Card><CardHeader><CardTitle>{t("createBrand")}</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => void submit(event)}><Field id="brand-name" label={t("name")} value={form.name} onChange={(value) => setForm((current) => ({...current, name: value}))} required /><div className="space-y-2"><Label htmlFor="brand-description">{t("description")}</Label><Textarea id="brand-description" value={form.description} onChange={(event) => setForm((current) => ({...current, description: event.target.value}))} /></div><Button type="submit" disabled={create.isPending}><Plus className="size-4" />{t("create")}</Button>{create.isError ? <div className="mt-3"><ErrorMessage error={create.error} /></div> : null}</form></CardContent></Card>{editing ? <BrandEditForm brand={editing} onClose={() => setEditing(null)} onSave={(request) => update.mutateAsync({id: editing.id!, request})} loading={update.isPending} error={update.error} /> : null}<Card><CardHeader><CardTitle>{t("brands")}</CardTitle></CardHeader><CardContent>{brands.isPending ? <div className="h-24 animate-pulse rounded-xl bg-muted" /> : brands.isError ? <ErrorMessage error={brands.error} /> : <div className="space-y-2">{(brands.data ?? []).map((brand) => <div key={brand.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span><span className="font-medium">{brand.name}</span><span className="ml-2 text-muted-foreground">{brand.status}</span></span>{brand.id ? <div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => setEditing(brand)} aria-label={t("editBrand")}><Pencil className="size-4" /></Button><Button size="icon-sm" variant="ghost" className="text-destructive hover:text-destructive" onClick={() => {if (window.confirm(t("confirmDelete"))) void remove.mutateAsync(brand.id!);}} disabled={remove.isPending} aria-label={t("delete")}><Trash2 className="size-4" /></Button></div> : null}</div>)}</div>}{remove.isError ? <div className="mt-4"><ErrorMessage error={remove.error} /></div> : null}</CardContent></Card></section>;
}

function BrandEditForm({brand, onClose, onSave, loading, error}: {brand: Brand; onClose: () => void; onSave: (request: {name: string; description?: string; status?: string}) => Promise<unknown>; loading: boolean; error: unknown}) {
  const t = useTranslations("admin");
  const [form, setForm] = useState({name: brand.name ?? "", description: brand.description ?? "", status: brand.status ?? "ACTIVE"});
  async function submit(event: FormEvent) { event.preventDefault(); await onSave({name: form.name.trim(), description: form.description.trim() || undefined, status: form.status}); onClose(); }
  return <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>{t("editBrand")}</CardTitle><Button size="icon-sm" variant="ghost" onClick={onClose} aria-label={t("close")}><X className="size-4" /></Button></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => void submit(event)}><Field id="edit-brand-name" label={t("name")} value={form.name} onChange={(value) => setForm((current) => ({...current, name: value}))} required /><div className="space-y-2"><Label htmlFor="edit-brand-status">{t("status")}</Label><Select id="edit-brand-status" value={form.status} onChange={(event) => setForm((current) => ({...current, status: event.target.value}))}><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></Select></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="edit-brand-description">{t("description")}</Label><Textarea id="edit-brand-description" value={form.description} onChange={(event) => setForm((current) => ({...current, description: event.target.value}))} /></div><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={loading}>{t("save")}</Button><Button type="button" variant="outline" onClick={onClose}>{t("cancel")}</Button></div>{error ? <div className="sm:col-span-2"><ErrorMessage error={error} /></div> : null}</form></CardContent></Card>;
}

export function ProductCreateForm() {
  const t = useTranslations("admin");
  const categories = useCategories();
  const brands = useBrands();
  const create = useCreateAdminProduct();
  const [form, setForm] = useState({name: "", seoName: "", categoryId: "", brandId: "", description: ""});
  async function submit(event: FormEvent) { event.preventDefault(); await create.mutateAsync({name: form.name.trim(), seoName: form.seoName.trim(), categoryId: form.categoryId, brandId: form.brandId || undefined, description: form.description.trim() || undefined}); setForm({name: "", seoName: "", categoryId: "", brandId: "", description: ""}); }
  return <Card className="mb-6"><CardHeader><CardTitle>{t("createProduct")}</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => void submit(event)}><Field id="product-name" label={t("name")} value={form.name} onChange={(value) => setForm((current) => ({...current, name: value}))} required /><Field id="product-seo" label={t("seoName")} value={form.seoName} onChange={(value) => setForm((current) => ({...current, seoName: value}))} required /><div className="space-y-2"><Label htmlFor="product-category">{t("category")}</Label><Select id="product-category" value={form.categoryId} onChange={(event) => setForm((current) => ({...current, categoryId: event.target.value}))} required><option value="">{t("chooseCategory")}</option>{flatten(categories.data ?? []).map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</Select></div><div className="space-y-2"><Label htmlFor="product-brand">{t("brand")}</Label><Select id="product-brand" value={form.brandId} onChange={(event) => setForm((current) => ({...current, brandId: event.target.value}))}><option value="">{t("noBrand")}</option>{(brands.data ?? []).filter((brand) => brand.status === "ACTIVE").map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</Select></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="product-description">{t("description")}</Label><Textarea id="product-description" value={form.description} onChange={(event) => setForm((current) => ({...current, description: event.target.value}))} /></div><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={create.isPending || !form.categoryId}><Plus className="size-4" />{t("create")}</Button>{create.isError ? <ErrorMessage error={create.error} /> : null}</div></form></CardContent></Card>;
}

function Field({id, label, value, onChange, required}: {id: string; label: string; value: string; onChange: (value: string) => void; required?: boolean}) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></div>; }
function flatten(categories: CategoryTree[], depth = 0): {id: string; label: string}[] { return categories.flatMap((category) => [...(category.id ? [{id: category.id, label: `${"— ".repeat(depth)}${category.name ?? ""}`}] : []), ...flatten(category.children ?? [], depth + 1)]); }
