"use client";

import {Plus} from "lucide-react";
import {useTranslations} from "next-intl";
import {useState, type FormEvent} from "react";

import {Button} from "@/components/ui/button";
import {Card, CardContent, CardDescription, CardHeader, CardTitle} from "@/components/ui/card";
import {ErrorMessage} from "@/components/ui/error-message";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select} from "@/components/ui/select";
import {Textarea} from "@/components/ui/textarea";
import type {CategoryTree} from "@/lib/api/types";

import {useCategories} from "@/features/catalog/queries";
import {useCreateAdminDiscount, useCreateAdminEmployee, useCreateAdminSupplier, useRoles} from "./queries";

function Field({id, label, value, onChange, type = "text", required}: {id: string; label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean}) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></div>; }
function flatten(categories: CategoryTree[], depth = 0): {id: string; label: string}[] { return categories.flatMap((category) => [...(category.id ? [{id: category.id, label: `${"— ".repeat(depth)}${category.name ?? ""}`}] : []), ...flatten(category.children ?? [], depth + 1)]); }
function iso(value: string) { return value ? new Date(value).toISOString() : new Date().toISOString(); }

export function EmployeeCreateForm() {
  const t = useTranslations("admin");
  const roles = useRoles();
  const create = useCreateAdminEmployee();
  const [form, setForm] = useState({fullName: "", email: "", phone: "", password: "", gender: "MALE", roleId: "", salary: "0", joinedAt: "", birthday: "", address: ""});
  function set(key: keyof typeof form, value: string) { setForm((current) => ({...current, [key]: value})); }
  async function submit(event: FormEvent) { event.preventDefault(); await create.mutateAsync({fullName: form.fullName.trim(), email: form.email.trim(), phone: form.phone.trim(), password: form.password, gender: form.gender, roleId: form.roleId, salary: Number(form.salary), joinedAt: form.joinedAt || undefined, birthday: form.birthday || undefined, address: form.address.trim() || undefined}); setForm({fullName: "", email: "", phone: "", password: "", gender: "MALE", roleId: "", salary: "0", joinedAt: "", birthday: "", address: ""}); }
  return <Card className="mb-6"><CardHeader><CardTitle>{t("createEmployee")}</CardTitle><CardDescription>{t("employeeCreateDescription")}</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => void submit(event)}><Field id="new-employee-name" label={t("fullName")} value={form.fullName} onChange={(value) => set("fullName", value)} required /><Field id="new-employee-email" label={t("email")} type="email" value={form.email} onChange={(value) => set("email", value)} required /><Field id="new-employee-phone" label={t("phone")} value={form.phone} onChange={(value) => set("phone", value)} required /><Field id="new-employee-password" label={t("initialPassword")} type="password" value={form.password} onChange={(value) => set("password", value)} required /><div className="space-y-2"><Label htmlFor="new-employee-role">{t("role")}</Label><Select id="new-employee-role" value={form.roleId} onChange={(event) => set("roleId", event.target.value)} required><option value="">{t("chooseRole")}</option>{(roles.data ?? []).map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</Select></div><div className="space-y-2"><Label htmlFor="new-employee-gender">{t("gender")}</Label><Select id="new-employee-gender" value={form.gender} onChange={(event) => set("gender", event.target.value)}><option value="MALE">{t("male")}</option><option value="FEMALE">{t("female")}</option></Select></div><Field id="new-employee-salary" label={t("salary")} type="number" value={form.salary} onChange={(value) => set("salary", value)} /><Field id="new-employee-joined" label={t("joinedAt")} type="date" value={form.joinedAt} onChange={(value) => set("joinedAt", value)} /><Field id="new-employee-birthday" label={t("birthday")} type="date" value={form.birthday} onChange={(value) => set("birthday", value)} /><div className="space-y-2 sm:col-span-2"><Label htmlFor="new-employee-address">{t("address")}</Label><Textarea id="new-employee-address" value={form.address} onChange={(event) => set("address", event.target.value)} /></div><div className="sm:col-span-2"><Button type="submit" disabled={create.isPending || !form.roleId}><Plus className="size-4" />{t("create")}</Button></div>{create.isError ? <div className="sm:col-span-2"><ErrorMessage error={create.error} /></div> : null}</form></CardContent></Card>;
}

export function SupplierCreateForm() {
  const t = useTranslations("admin");
  const create = useCreateAdminSupplier();
  const [form, setForm] = useState({name: "", email: "", phone: "", address: "", description: ""});
  async function submit(event: FormEvent) { event.preventDefault(); await create.mutateAsync({name: form.name.trim(), email: form.email.trim() || undefined, phone: form.phone.trim() || undefined, address: form.address.trim() || undefined, description: form.description.trim() || undefined}); setForm({name: "", email: "", phone: "", address: "", description: ""}); }
  return <Card className="mb-6"><CardHeader><CardTitle>{t("createSupplier")}</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => void submit(event)}><Field id="new-supplier-name" label={t("name")} value={form.name} onChange={(value) => setForm((current) => ({...current, name: value}))} required /><Field id="new-supplier-email" label={t("email")} type="email" value={form.email} onChange={(value) => setForm((current) => ({...current, email: value}))} /><Field id="new-supplier-phone" label={t("phone")} value={form.phone} onChange={(value) => setForm((current) => ({...current, phone: value}))} /><Field id="new-supplier-address" label={t("address")} value={form.address} onChange={(value) => setForm((current) => ({...current, address: value}))} /><div className="space-y-2 sm:col-span-2"><Label htmlFor="new-supplier-description">{t("description")}</Label><Textarea id="new-supplier-description" value={form.description} onChange={(event) => setForm((current) => ({...current, description: event.target.value}))} /></div><div className="sm:col-span-2"><Button type="submit" disabled={create.isPending || !form.name.trim()}><Plus className="size-4" />{t("create")}</Button></div>{create.isError ? <div className="sm:col-span-2"><ErrorMessage error={create.error} /></div> : null}</form></CardContent></Card>;
}

export function DiscountCreateForm() {
  const t = useTranslations("admin");
  const categories = useCategories();
  const create = useCreateAdminDiscount();
  const [form, setForm] = useState({title: "", code: "", discountType: "PERCENT", value: "10", applicationScope: "ORDER", minOrderAmount: "0", startAt: "", endAt: "", description: "", categoryIds: [] as string[], variantIds: ""});
  function set(key: keyof typeof form, value: string | string[]) { setForm((current) => ({...current, [key]: value})); }
  async function submit(event: FormEvent) { event.preventDefault(); await create.mutateAsync({title: form.title.trim(), code: form.code.trim() || undefined, discountType: form.discountType, value: Number(form.value), applicationScope: form.applicationScope, minOrderAmount: Number(form.minOrderAmount), startAt: iso(form.startAt), endAt: iso(form.endAt), description: form.description.trim() || undefined, appliedCategoryIds: form.applicationScope === "CATEGORY" ? form.categoryIds : [], appliedVariantIds: form.applicationScope === "VARIANT" ? form.variantIds.split(",").map((id) => id.trim()).filter(Boolean) : []}); setForm({title: "", code: "", discountType: "PERCENT", value: "10", applicationScope: "ORDER", minOrderAmount: "0", startAt: "", endAt: "", description: "", categoryIds: [], variantIds: ""}); }
  const targetError = (form.applicationScope === "CATEGORY" && form.categoryIds.length === 0) || (form.applicationScope === "VARIANT" && !form.variantIds.trim());
  return <Card className="mb-6"><CardHeader><CardTitle>{t("createDiscount")}</CardTitle><CardDescription>{t("discountTargetDescription")}</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => void submit(event)}><Field id="new-discount-title" label={t("titleField")} value={form.title} onChange={(value) => set("title", value)} required /><Field id="new-discount-code" label={t("code")} value={form.code} onChange={(value) => set("code", value)} /><div className="space-y-2"><Label htmlFor="new-discount-type">{t("discountType")}</Label><Select id="new-discount-type" value={form.discountType} onChange={(event) => set("discountType", event.target.value)}><option value="PERCENT">PERCENT</option><option value="FIXED">FIXED</option></Select></div><Field id="new-discount-value" label={t("value")} type="number" value={form.value} onChange={(value) => set("value", value)} required /><Field id="new-discount-start" label={t("startAt")} type="datetime-local" value={form.startAt} onChange={(value) => set("startAt", value)} required /><Field id="new-discount-end" label={t("endAt")} type="datetime-local" value={form.endAt} onChange={(value) => set("endAt", value)} required /><Field id="new-discount-min" label={t("minOrderAmount")} type="number" value={form.minOrderAmount} onChange={(value) => set("minOrderAmount", value)} /><div className="space-y-2"><Label htmlFor="new-discount-scope">{t("applicationScope")}</Label><Select id="new-discount-scope" value={form.applicationScope} onChange={(event) => set("applicationScope", event.target.value)}><option value="ORDER">ORDER</option><option value="ALL_ITEMS">ALL_ITEMS</option><option value="CATEGORY">CATEGORY</option><option value="VARIANT">VARIANT</option></Select></div>{form.applicationScope === "CATEGORY" ? <div className="space-y-2 sm:col-span-2"><Label htmlFor="new-discount-categories">{t("targetCategories")}</Label><Select id="new-discount-categories" multiple value={form.categoryIds} onChange={(event) => set("categoryIds", Array.from(event.target.selectedOptions).map((option) => option.value))} className="min-h-28">{flatten(categories.data ?? []).map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</Select></div> : null}{form.applicationScope === "VARIANT" ? <Field id="new-discount-variants" label={t("targetVariantIds")} value={form.variantIds} onChange={(value) => set("variantIds", value)} /> : null}<div className="space-y-2 sm:col-span-2"><Label htmlFor="new-discount-description">{t("description")}</Label><Textarea id="new-discount-description" value={form.description} onChange={(event) => set("description", event.target.value)} /></div><div className="sm:col-span-2"><Button type="submit" disabled={create.isPending || targetError}><Plus className="size-4" />{t("create")}</Button></div>{create.isError ? <div className="sm:col-span-2"><ErrorMessage error={create.error} /></div> : null}</form></CardContent></Card>;
}
