"use client";

import {Search, Trash2} from "lucide-react";
import {useLocale, useTranslations} from "next-intl";
import {useState, type ReactNode} from "react";

import {Button} from "@/components/ui/button";
import {Card, CardContent} from "@/components/ui/card";
import {ErrorMessage} from "@/components/ui/error-message";
import {Input} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {StatusBadge} from "@/components/ui/status-badge";
import {Link} from "@/i18n/navigation";
import {formatMoney} from "@/lib/format";

import {useAdminCustomerStatus, useAdminCustomers, useAdminDiscounts, useAdminDiscountStatus, useAdminEmployeeStatus, useAdminEmployees, useAdminOrderStatus, useAdminOrders, useAdminPaymentMethods, useAdminPayments, useAdminPaymentStatus, useAdminProductStatus, useAdminProducts, useAdminReviews, useAdminReviewStatus, useAdminSuppliers, useDeleteAdminProduct} from "./queries";
import {ProductCreateForm} from "./catalog-management";
import {AdminInvoicesPage} from "./detail-pages";
import {DiscountCreateForm, EmployeeCreateForm, SupplierCreateForm} from "./management-forms";

export type AdminResource = "products" | "orders" | "customers" | "employees" | "discounts" | "suppliers" | "payments" | "payment-methods" | "reviews" | "invoices";

export function AdminResourcePage({resource}: {resource: AdminResource}) {
  switch (resource) {
    case "products": return <Products />;
    case "orders": return <Orders />;
    case "customers": return <Customers />;
    case "employees": return <Employees />;
    case "discounts": return <Discounts />;
    case "suppliers": return <Suppliers />;
    case "payments": return <Payments />;
    case "payment-methods": return <PaymentMethods />;
    case "reviews": return <Reviews />;
    case "invoices": return <AdminInvoicesPage />;
  }
}

function Heading({title, description}: {title: string; description: string}) { return <div className="mb-8"><p className="eyebrow">{title}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p></div>; }
function Filter({value, onChange, placeholder, status, onStatus, onSubmit}: {value: string; onChange: (value: string) => void; placeholder: string; status?: string; onStatus?: (value: string) => void; onSubmit?: () => void}) { const t = useTranslations("admin"); return <div className="mb-5 flex flex-col gap-3 sm:flex-row"><form className="flex flex-1 gap-2" onSubmit={(event) => {event.preventDefault(); onSubmit?.();}}><Input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /><Button type="submit"><Search className="size-4" />{t("search")}</Button></form>{onStatus ? <Select className="sm:w-56" value={status} onChange={(event) => onStatus(event.target.value)}><option value="">{t("allStatuses")}</option><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option><option value="PENDING_PAYMENT">PENDING_PAYMENT</option><option value="PENDING_CONFIRMATION">PENDING_CONFIRMATION</option><option value="CONFIRMED">CONFIRMED</option><option value="SHIPPING">SHIPPING</option><option value="COMPLETED">COMPLETED</option><option value="CANCELLED">CANCELLED</option><option value="PAID">PAID</option><option value="FAILED">FAILED</option></Select> : null}</div>; }
function Shell({title, description, children}: {title: string; description: string; children: ReactNode}) { return <div><Heading title={title} description={description} />{children}</div>; }
function Loading() { return <div className="h-64 animate-pulse rounded-2xl bg-muted" />; }
function Failure({error}: {error: unknown}) { return <ErrorMessage error={error} />; }

function Products() { const t = useTranslations("admin"); const locale = useLocale(); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const [applied, setApplied] = useState({keyword: "", status: ""}); const query = useAdminProducts({limit: 20, keyword: applied.keyword || undefined, status: applied.status || undefined}); const mutation = useAdminProductStatus(); const remove = useDeleteAdminProduct(); return <Shell title={t("resource.products")} description={t("resource.productsDescription")}><ProductCreateForm /><Filter value={keyword} onChange={setKeyword} placeholder={t("searchProducts")} status={status} onStatus={(value) => {setStatus(value); setApplied((current) => ({...current, status: value}));}} onSubmit={() => setApplied({keyword: keyword.trim(), status})} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <div className="space-y-3">{(query.data?.items ?? []).map((product, index) => <Card key={product.id ?? index}><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div>{product.id ? <Link href={`/admin/products/${product.id}`} className="font-semibold hover:underline">{product.name}</Link> : <p className="font-semibold">{product.name}</p>}<p className="mt-1 text-sm text-muted-foreground">{product.brandName ?? "—"} · {formatMoney(product.minPrice, locale)}</p></div><div className="flex items-center gap-3"><StatusBadge status={product.status} />{product.id ? <Select className="h-8 w-32" value={product.status ?? ""} onChange={(event) => void mutation.mutateAsync({id: product.id!, status: event.target.value})}><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></Select> : null}{product.id ? <Button size="icon-sm" variant="ghost" className="text-destructive hover:text-destructive" aria-label={t("delete")} onClick={() => {if (window.confirm(t("confirmDelete"))) void remove.mutateAsync(product.id!);}} disabled={remove.isPending}><Trash2 className="size-4" /></Button> : null}</div></CardContent></Card>)}</div>}{remove.isError ? <div className="mt-4"><Failure error={remove.error} /></div> : null}</Shell>; }

function Orders() { const t = useTranslations("admin"); const locale = useLocale(); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const query = useAdminOrders({limit: 20, keyword: keyword || undefined, status: status || undefined}); const mutation = useAdminOrderStatus(); return <Shell title={t("resource.orders")} description={t("resource.ordersDescription")}><Filter value={keyword} onChange={setKeyword} placeholder={t("searchOrders")} status={status} onStatus={setStatus} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <div className="space-y-3">{(query.data?.items ?? []).map((order, index) => <Card key={order.id ?? index}><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div>{order.id ? <Link href={`/admin/orders/${order.id}`} className="font-semibold hover:underline">{order.id}</Link> : <p className="font-semibold">—</p>}<p className="mt-1 text-sm text-muted-foreground">{order.customerName ?? order.customerEmail ?? "—"} · {formatMoney(order.totalAmount, locale)}</p></div><div className="flex items-center gap-3"><StatusBadge status={order.status} />{order.id ? <Select className="h-8 w-48" value={order.status ?? ""} onChange={(event) => void mutation.mutateAsync({id: order.id!, status: event.target.value})}><option value="PENDING_PAYMENT">PENDING_PAYMENT</option><option value="PENDING_CONFIRMATION">PENDING_CONFIRMATION</option><option value="CONFIRMED">CONFIRMED</option><option value="SHIPPING">SHIPPING</option><option value="COMPLETED">COMPLETED</option><option value="CANCELLED">CANCELLED</option></Select> : null}</div></CardContent></Card>)}</div>}</Shell>; }

function Customers() { const t = useTranslations("admin"); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const query = useAdminCustomers({limit: 20, keyword: keyword || undefined, status: status || undefined}); const mutation = useAdminCustomerStatus(); return <Shell title={t("resource.customers")} description={t("resource.customersDescription")}><Filter value={keyword} onChange={setKeyword} placeholder={t("searchCustomers")} status={status} onStatus={setStatus} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <ListRows rows={(query.data?.items ?? []).map((customer) => ({id: customer.accountId ?? customer.id, title: customer.fullName ?? "—", meta: `${customer.email ?? "—"} · ${customer.phone ?? "—"}`, status: customer.status, href: (customer.accountId ?? customer.id) ? `/admin/customers/${customer.accountId ?? customer.id}` : undefined}))} onStatus={(id, value) => void mutation.mutateAsync({id, status: value})} />}</Shell>; }

function Employees() { const t = useTranslations("admin"); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const query = useAdminEmployees({limit: 20, keyword: keyword || undefined, status: status || undefined}); const mutation = useAdminEmployeeStatus(); return <Shell title={t("resource.employees")} description={t("resource.employeesDescription")}><EmployeeCreateForm /><Filter value={keyword} onChange={setKeyword} placeholder={t("searchEmployees")} status={status} onStatus={setStatus} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <ListRows rows={(query.data?.items ?? []).map((employee) => ({id: employee.accountId ?? employee.id, title: employee.fullName ?? "—", meta: `${employee.roleName ?? "—"} · ${employee.email ?? "—"}`, status: employee.status, href: (employee.accountId ?? employee.id) ? `/admin/employees/${employee.accountId ?? employee.id}` : undefined}))} onStatus={(id, value) => void mutation.mutateAsync({id, status: value})} />}</Shell>; }

function Discounts() { const t = useTranslations("admin"); const locale = useLocale(); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const query = useAdminDiscounts({limit: 20, keyword: keyword || undefined, status: status || undefined}); const mutation = useAdminDiscountStatus(); return <Shell title={t("resource.discounts")} description={t("resource.discountsDescription")}><DiscountCreateForm /><Filter value={keyword} onChange={setKeyword} placeholder={t("searchDiscounts")} status={status} onStatus={setStatus} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <div className="space-y-3">{(query.data?.items ?? []).map((discount, index) => <Card key={discount.id ?? index}><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div>{discount.id ? <Link href={`/admin/discounts/${discount.id}`} className="font-semibold hover:underline">{discount.code ?? discount.title}</Link> : <p className="font-semibold">{discount.code ?? discount.title}</p>}<p className="mt-1 text-sm text-muted-foreground">{discount.title} · {discount.discountType} {discount.value} · min {formatMoney(discount.minOrderAmount, locale)}</p></div><div className="flex items-center gap-3"><StatusBadge status={discount.status} />{discount.id ? <Select className="h-8 w-32" value={discount.status ?? ""} onChange={(event) => void mutation.mutateAsync({id: discount.id!, status: event.target.value})}><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option><option value="DISABLED">DISABLED</option><option value="EXPIRED">EXPIRED</option></Select> : null}</div></CardContent></Card>)}</div>}</Shell>; }

function Suppliers() { const t = useTranslations("admin"); const [keyword, setKeyword] = useState(""); const query = useAdminSuppliers({limit: 20, keyword: keyword || undefined}); return <Shell title={t("resource.suppliers")} description={t("resource.suppliersDescription")}><SupplierCreateForm /><Filter value={keyword} onChange={setKeyword} placeholder={t("searchSuppliers")} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <ListRows rows={(query.data?.items ?? []).map((supplier) => ({id: supplier.id, title: supplier.name ?? "—", meta: `${supplier.email ?? "—"} · ${supplier.phone ?? "—"}`, status: supplier.status, href: supplier.id ? `/admin/suppliers/${supplier.id}` : undefined}))} />}</Shell>; }

function Payments() { const t = useTranslations("admin"); const locale = useLocale(); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const query = useAdminPayments({limit: 20, keyword: keyword || undefined, status: status || undefined}); const mutation = useAdminPaymentStatus(); return <Shell title={t("resource.payments")} description={t("resource.paymentsDescription")}><Filter value={keyword} onChange={setKeyword} placeholder={t("searchPayments")} status={status} onStatus={setStatus} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <div className="space-y-3">{(query.data?.items ?? []).map((payment, index) => <Card key={payment.id ?? index}><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-semibold">{payment.providerTransactionCode ?? payment.id}</p><p className="mt-1 text-sm text-muted-foreground">{payment.paymentMethodCode ?? "—"} · {formatMoney(payment.amount, locale)}</p></div><div className="flex items-center gap-3"><StatusBadge status={payment.status} />{payment.id ? <Select className="h-8 w-32" value={payment.status ?? ""} onChange={(event) => void mutation.mutateAsync({id: payment.id!, status: event.target.value})}><option value="PENDING">PENDING</option><option value="PAID">PAID</option><option value="FAILED">FAILED</option></Select> : null}</div></CardContent></Card>)}</div>}</Shell>; }

function PaymentMethods() { const t = useTranslations("admin"); const query = useAdminPaymentMethods(); return <Shell title={t("resource.paymentMethods")} description={t("resource.paymentMethodsDescription")}>{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <ListRows rows={(query.data ?? []).map((method) => ({id: method.id, title: method.name ?? method.code ?? "—", meta: method.code ?? "—", status: method.status}))} />}</Shell>; }

function Reviews() { const t = useTranslations("admin"); const [keyword, setKeyword] = useState(""); const query = useAdminReviews({limit: 20, keyword: keyword || undefined}); const mutation = useAdminReviewStatus(); return <Shell title={t("resource.reviews")} description={t("resource.reviewsDescription")}><Filter value={keyword} onChange={setKeyword} placeholder={t("searchReviews")} />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} /> : <ListRows rows={(query.data?.items ?? []).map((review) => ({id: review.id, title: `${review.productName ?? "Product"} · ${review.rating}/5`, meta: review.comment ?? "—", status: review.status}))} onStatus={(id, value) => void mutation.mutateAsync({id, status: value})} review />}</Shell>; }

function ListRows({rows, onStatus, review}: {rows: {id?: string; title: string; meta: string; status?: string; href?: string}[]; onStatus?: (id: string, status: string) => void; review?: boolean}) { return <div className="space-y-3">{rows.map((row, index) => <Card key={row.id ?? index}><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div>{row.href ? <Link href={row.href} className="font-semibold hover:underline">{row.title}</Link> : <p className="font-semibold">{row.title}</p>}<p className="mt-1 text-sm text-muted-foreground">{row.meta}</p></div><div className="flex items-center gap-3"><StatusBadge status={row.status} />{onStatus && row.id ? <Select className="h-8 w-36" value={row.status ?? ""} onChange={(event) => void onStatus(row.id!, event.target.value)}><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option>{review ? <option value="DELETED">DELETED</option> : null}<option value="LOCKED">LOCKED</option></Select> : null}</div></CardContent></Card>)}</div>; }
